springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  

server:
  port: 8081
  servlet:
    context-path: /
  error:
    include-message: always  

es:
  microservices:
    tests:
      orders:
        orders-config:
          base-url: http://daas-orders:8083
          endpoint-url: /orders
        phones-config:          
          base-url: http://daas-phones:8082
          endpoint-url: /phones

